# Generated by Django 3.2.19 on 2023-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20230531_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('registered', 'Registered'), ('accepted', 'Accepted'), ('delivered', 'Delivered'), ('closed', 'Closed')], max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
